@file:OptIn(ExperimentalTime::class)

package io.writeopia.sdk.models.presentation

import io.writeopia.sdk.models.id.GenerateId
import kotlin.time.ExperimentalTime
import kotlin.time.Instant

/**
 * A presentation generated by the AI from a document.
 */
data class Presentation(
    val id: String = GenerateId.generate(),
    val documentId: String,
    val workspaceId: String,
    val userId: String? = null,
    val title: String,
    val createdAt: Instant,
    val slides: List<Slide> = emptyList()
)
