name: Setup Java 17
description: Sets up the java 17

runs:
  steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '17'