services:
  postgres:
    image: postgres:latest
    container_name: writeopia-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: writeopia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
  gateway:
    image: ghcr.io/writeopia/writeopia-backend:latest
    container_name: writeopia-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"  # Map container's port 8080 to host port 8080
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/writeopia
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    restart: unless-stopped
#  ai-hub:
#    image: ghcr.io/writeopia/writeopia-ai-hub:latest
#    container_name: writeopia-ai-hub
#    ports:
#      - "8000:8000"
#    restart: unless-stopped

volumes:
  postgres_data:


