package io.writeopia.editor.features.presentation.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import io.writeopia.editor.features.editor.ui.publish.PremiumOnlyDialog
import io.writeopia.editor.features.presentation.viewmodel.PresentationsController
import io.writeopia.sdk.models.presentation.Presentation

/**
 * The dialogs of the presentations of a document, shared by every platform: the list with the
 * "create new" button, the premium notice, and the opening of a presentation just made. How a
 * presentation is shown is up to the platform (`open`): a window on desktop, full screen on mobile.
 */
@Composable
fun PresentationsHost(controller: PresentationsController, open: (Presentation) -> Unit) {
    val showDialog by controller.showDialog.collectAsState()
    val premiumRequested by controller.premiumRequested.collectAsState()
    val generated by controller.generated.collectAsState()

    LaunchedEffect(generated) {
        val presentation = generated ?: return@LaunchedEffect
        controller.consumeGenerated()
        controller.hideDialog()
        open(presentation)
    }

    if (showDialog) {
        PresentationsDialog(
            controller = controller,
            onOpen = { presentation ->
                controller.hideDialog()
                open(presentation)
            },
            onDismiss = controller::hideDialog
        )
    }

    if (premiumRequested) {
        PremiumOnlyDialog(onDismiss = controller::dismissPremium)
    }
}
