name: Build and test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  android_build_and_test:
    name: Android - build and test
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Configure Java 17
        uses: ./github/workflow_templates/setup-reusable.yml
      - name: Build android 
        run: ./gradlew backend:intronotes:assemble backend:intronotes:test
  backend_build_and_test:
    name: Backend - build and test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Configure Java 17
        uses: ./github/workflow_templates/setup-reusable.yml
      - name: Build backend
        run: ./gradlew assembleDebug testDebug