name: Build and test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  android_debug_build_and_test:
    name: Android - Test debug
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '17'
      - name: Build debug android 
        run: ./gradlew test
  android_build:
    name: General - Build debug
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '17'
      - name: Build debug android 
        run: ./gradlew assembleDebug
  backend_build_and_test:
    name: Backend - build and test
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '17'
      - name: Build backend
        run: ./gradlew backend:intronotes:assemble backend:intronotes:test
  test_docusaurus:
    name: Test docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: documentation/writeopia_docs/package-lock.json

      - name: Install dependencies
        working-directory: ./documentation/writeopia_docs
        run: yarn install --frozen-lockfile
      - name: Test build website
        working-directory: ./documentation/writeopia_docs
        run: yarn build