name: Build and test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  kt_lint:
    name: Ktlint
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '21'
      - name: Ktlint
        run: ./gradlew ktlintCheck --no-daemon
  ui_jvm_tests:
    name: Jvm UI Compose tests
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
      IN_MEMORY_DATABASE: 'true'
      DB_USER: 'user'
      WRITEOPIA_FIREBASE_ID: 'id'
      WRITEOPIA_CLIENT_BASE_URL: "baseurl"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '21'
      - name: JVM tests
        run: ./gradlew jvmTest --no-daemon
      - name: upload results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results-jvm
          path: ./application/desktopApp/build/reports/
  general_build:
    name: General - Build debug
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '21'
      - name: Build debug
        run: ./gradlew assembleDebug test --no-daemon
  ios_build:
    name: iOS build
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '21'
      - name: Build debug
        run: ./gradlew compileKotlinIosArm64 --no-daemon
  backend_build_and_test:
    name: Backend - build
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
      IN_MEMORY_DATABASE: 'true'
      DB_USER: 'user'
      WRITEOPIA_FIREBASE_ID: 'id'
      WRITEOPIA_CLIENT_BASE_URL: "baseurl"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '21'
      - name: Build backend
        run: ./gradlew backend:documents:documents_spring:assemble backend:editor:api_editor:assemble backend:editor:api_editor:test backend:editor:api_editor_socket:assemble backend:editor:api_editor_socket:test --no-daemon
      - name: upload results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results-backend
          path: ./backend/editor/api_editor_spring/build/reports/
  web_build:
    name: Web - Build debug
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '21'
      - name: Build web debug
        run: ./gradlew jsBrowserDevelopmentWebpack --no-daemon
  test_docusaurus:
    name: Test docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: documentation/writeopia_docs/package-lock.json
      - name: Install dependencies
        working-directory: ./documentation/writeopia_docs
        run: npm ci
      - name: Test build website
        working-directory: ./documentation/writeopia_docs
        run: npm run build


