name: PR checks

on: [pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  debug_build:
    name: Debug build and unit tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '17'
      - name: Build and unit tests
        run: ./gradlew assembleDebug testDebug backend:intronotes:assemble backend:intronotes:test
  android_integration_tests:
    name: 
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: '17'
      - name: UI tests
        run: ./gradlew application:app:pixel6api31DebugAndroidTest